/** Theme + phase tips — mirrors anthropic_theme.py · versions: requirements_manifest.py */

window.LEARNING_CONFIG = {
  /** Must match curriculum/requirements_manifest.py — run generate_all_learning.py after bump */
  APP_VERSION: "2.5.0",
  REQUIREMENTS_VERSION: "2.0.0",
  CURRICULUM_VERSION: "1.3",
  MANIFEST_URL: "data/requirements-manifest.json",
  FILES_URL: "data/app-files-manifest.json",
  DATA_URL: "data/learning-data.json",
  STORAGE_KEY: "learning-ai-learning-progress",
  NAV: [
    { id: "landing", label: "Home", hash: "landing", icon: "home" },
    { id: "dashboard", label: "Dashboard", hash: "dashboard", icon: "dashboard" },
    { id: "explore", label: "Explore", hash: "explore", icon: "explore" },
    { id: "library", label: "Library", hash: "library", icon: "library" },
    { id: "account", label: "Account", hash: "auth", icon: "account" },
  ],
  NAV_EXTERNAL: [{ label: "BRD", href: "brd/", icon: "brd" }],
  PHASE_COLORS: {
    y1q1: "var(--clay)",
    y1q2: "var(--sky)",
    y1q3: "var(--fig)",
    y1q4: "var(--olive)",
    // legacy ids (fallback)
    foundation: "var(--clay)",
    ml: "var(--sky)",
    nlp: "var(--olive)",
    genai: "var(--fig)",
    production: "var(--cactus)",
    career: "var(--olive)",
  },
  PHASE_TIPS: {
    y1q1: "Prove you can ship — BRD scorer + SQL/pandas before any ML math.",
    y1q2: "Portfolio piece 1 — PD model + value case (H1) beats tutorial certificates.",
    y1q3: "Portfolio piece 2 — RAG + agent + Docker API = OCB/NAB interview core.",
    y1q4: "Apply AI Engineer — CV, STAR, mock interview; Track B deck for leadership loops.",
    foundation: "Type every example yourself — no copy-paste. Commit when the script runs clean.",
    ml: "Connect every metric to business language: NPL, false decline, approval rate.",
    nlp: "Always log which source chunk grounded your answer.",
    genai: "Refuse when context is missing — escalation is a feature, not failure.",
    production: "If a friend cannot curl your API, it is not done.",
    career: "Quantify impact in VND or bps — hiring managers need numbers.",
  },
  /** Served at /decks/ on GitHub Pages; synced from exports/learning/ on generate */
  DECK_BASE: "decks/",
  REPO: "https://github.com/taiphan/learning",
  REPO_BLOB: "https://github.com/taiphan/learning/blob/main",
  DECKS: [
    { id: "master", label: "52-Week Master (165 slides)", file: "Learning-Master-Slides.pptx" },
    { id: "roadmap", label: "Zero-to-AI Roadmap", file: "Zero-to-AI-Expert-Roadmap-Slides.pptx" },
    { id: "trackb", label: "Track B — Head of AI (VPBank-aligned)", file: "Learning-Track-B-Slides.pptx" },
  ],
  /** Track B deliverable filenames under lab/delivery/track-b/ */
  TRACK_B_DELIVERY: {
    H0: "h0-ai-strategy.md",
    H1: "h1-pd-value-case.md",
    H2: "h2-copilot-governance.md",
    H3: "h3-ninety-day-plan.md",
    H4: "h4-steering-deck.md",
  },
  GUIDE_STORAGE_KEY: "learning-guide-v1-completed",
  GUIDE_HOME_CARD_KEY: "learning-guide-home-card-dismissed",
  USAGE_DOC: "https://github.com/taiphan/learning/blob/main/docs/learning-requirements/LEARNING-REQUIREMENTS.md",
  CHANGELOG_DOC: "https://github.com/taiphan/learning/blob/main/docs/learning-requirements/CHANGELOG.md",
  ENRICHMENT_DOC: "https://github.com/taiphan/learning/blob/main/curriculum/video-learning-enrichment.md",
  ENRICHMENT: [
    {
      quarter: "Y1 Q1",
      weeks: "1–12",
      items: [
        { label: "Coursera — Python for Everybody (Michigan)", url: "https://www.coursera.org/specializations/python", tag: "Coursera" },
        { label: "Kaggle Learn — Python, SQL, pandas", url: "https://www.kaggle.com/learn", tag: "Free" },
        { label: "Coursera — IBM SQL for Data Science", url: "https://www.coursera.org/learn/sql-data-science", tag: "Coursera" },
        { label: "YouTube — StatQuest", url: "https://www.youtube.com/@statquest", tag: "YouTube" },
      ],
    },
    {
      quarter: "Y1 Q2",
      weeks: "13–24",
      items: [
        { label: "Coursera — Supervised ML (Andrew Ng)", url: "https://www.coursera.org/learn/machine-learning", tag: "Coursera" },
        { label: "Coursera — ML with Python (IBM)", url: "https://www.coursera.org/learn/machine-learning-with-python", tag: "Coursera" },
        { label: "Kaggle — Intro to ML", url: "https://www.kaggle.com/learn/intro-to-machine-learning", tag: "Free" },
        { label: "Hugging Face NLP Course", url: "https://huggingface.co/learn/nlp-course/chapter1/1", tag: "Free" },
      ],
    },
    {
      quarter: "Y1 Q3",
      weeks: "25–36",
      items: [
        { label: "DeepLearning.AI short courses", url: "https://www.deeplearning.ai/courses/", tag: "Free" },
        { label: "YouTube — LangChain RAG From Scratch", url: "https://www.youtube.com/playlist?list=PLfaIDFEXuae2LXbO1_PKyVJiQ23ZztA0x", tag: "YouTube" },
        { label: "Microsoft — AI Agents for Beginners", url: "https://github.com/microsoft/ai-agents-for-beginners", tag: "Free" },
        { label: "Coursera — Generative AI for Everyone", url: "https://www.coursera.org/learn/generative-ai-for-everyone", tag: "Coursera" },
      ],
    },
    {
      quarter: "Y1 Q4",
      weeks: "37–52",
      items: [
        { label: "Coursera — AI For Everyone", url: "https://www.coursera.org/learn/ai-for-everyone", tag: "Coursera" },
        { label: "Coursera — AWS Prompt Engineering (free)", url: "https://www.coursera.org/learn/essentials-of-prompt-engineering", tag: "Free" },
        { label: "Class Central — 270+ free Coursera", url: "https://www.classcentral.com/report/coursera-free-online-courses/", tag: "Index" },
        { label: "LinkedIn — Python for AI & ML path", url: "https://www.linkedin.com/learning/paths/develop-with-python-for-ai-and-machine-learning", tag: "LinkedIn" },
      ],
    },
  ],
  GUIDE_STEPS: [
    {
      id: "welcome",
      type: "center",
      title: "Welcome to your 52-week learning cockpit",
      body: "This app is your weekly plan for becoming an <strong>AI Engineer</strong> at a VN bank — built for banking BAs starting from zero Python.",
      tip: "Budget <strong>10 hours per week</strong>: ~8h technical (Track A) + leadership on milestone weeks (Track B).",
    },
    {
      id: "dual-track",
      type: "center",
      title: "Two tracks, one path",
      body: "<p><strong>Track A (~8h)</strong> — every week: Study tab → Lab tab → run Python in <code>lab/</code>.</p><p><strong>Track B (~2h)</strong> — weeks <strong>8, 16, 28, 40, 52</strong> only: Leadership tab → save to <code>lab/delivery/track-b/</code>.</p>",
    },
    {
      id: "menu",
      type: "spotlight",
      target: "#appNav",
      title: "Main menu",
      body: "<strong>Home</strong> — welcome & quick start · <strong>Dashboard</strong> — your progress · <strong>Explore</strong> — full path & resources · <strong>Library</strong> — all files · <strong>Account</strong> — sync · <strong>BRD</strong> — Week 1 bridge.",
    },
    {
      id: "continue",
      type: "spotlight",
      target: "#continueBtn",
      title: "Continue where you left off",
      body: "Click <strong>Continue</strong> anytime to jump to your next incomplete week.",
    },
    {
      id: "progress",
      type: "spotlight",
      target: ".topbar-stats",
      title: "Your progress at a glance",
      body: "<strong>B x/5</strong> = Track B milestones done · <strong>x / 52</strong> = weeks complete. Saved in this browser only.",
    },
    {
      id: "sidebar",
      type: "spotlight",
      target: "#sidebar",
      title: "Week list & checkpoints",
      body: "Browse all 52 weeks, filter by Y1 quarter, and track CP0–CP6 plus Head of AI (H0–H4) milestones. On mobile, tap ☰ to open.",
      before: "openSidebar",
    },
    {
      id: "track-b-home",
      type: "spotlight",
      target: "#hoaiHomeCard",
      title: "Head of AI track (Track B)",
      body: "Leadership milestones appear here. Click any row to jump to that week. First deliverable: <strong>H0 at Week 8</strong>.",
      view: "dashboard",
    },
    {
      id: "brd",
      type: "spotlight",
      target: ".app-nav-external",
      title: "BRD app — Week 1 bridge",
      body: "Week 1 connects your BA work to code: draft a BRD here, export <code>.md</code>, then run the checklist script from the Lab tab.",
    },
    {
      id: "week1",
      type: "center",
      title: "Let's open Week 1",
      body: "Next we'll show the <strong>weekly tabs</strong> — the loop you repeat every week.",
      before: "goWeek1",
    },
    {
      id: "tabs",
      type: "spotlight",
      target: ".tabs",
      title: "Your weekly loop",
      body: "<ol class='guide-steps-list'><li><strong>Overview</strong> — deliverable + bridge banner</li><li><strong>Study</strong> — readings (~2–3h)</li><li><strong>Lab</strong> — run exercises in <code>lab/</code> (~4–5h)</li><li><strong>Leadership</strong> — Track B on milestone weeks</li><li><strong>Notes</strong> — saved automatically</li></ol>",
      view: "week",
      week: 1,
    },
    {
      id: "bridge",
      type: "spotlight",
      target: "#weekBridge",
      title: "Week 1 — start here",
      body: "Follow the bridge: BRD app → export → run <code>python3 exercises/week01_brd_checklist.py your-export.md</code> from <code>lab/</code>.",
      view: "week",
      week: 1,
      before: "showOverviewTab",
    },
    {
      id: "lab-tab",
      type: "spotlight",
      target: "[data-tab='lab']",
      title: "Lab tab — hands-on work",
      body: "Copy the run command, open the exercise in Cursor, run from <code>lab/</code>. Mark the week complete only when output matches <strong>Done when</strong>.",
      view: "week",
      week: 1,
      before: "flashLabTab",
    },
    {
      id: "done",
      type: "center",
      title: "You're ready to learn",
      body: "<p>Repeat each week: <strong>Overview → Study → Lab</strong> (+ Leadership on milestone weeks) → mark complete.</p><p>Requirements doc: <a href='https://github.com/taiphan/learning/blob/main/docs/learning-requirements/LEARNING-REQUIREMENTS.md' target='_blank' rel='noopener'>LEARNING-REQUIREMENTS.md v2.0</a></p>",
      tip: "Reopen this tour anytime with the <strong>Guide</strong> button in the header.",
    },
  ],
};
